name: Main pipeline

on:
  push:
    branches:
      - feature/add-pipelines
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: List contents of TestWindow directory
        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Add path for VSTest
        run: echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run unit tests
        shell: cmd
        run: |
          msbuild VinaText.sln /t:Rebuild
          vstest.console.exe VinaText.dll

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Run dir command
        run: dir

      - name: Run echo command
        run: echo hello

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        shell: cmd
        run: msbuild VinaText.sln /p:Configuration=Release /p:Platform=x64